name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./HA2
          file: ./HA2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-app:latest

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Image build result for ${{ github.repository }}"
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: |
            Result: ${{ job.status }}
            Commit message: ${{ github.event.head_commit.message }}
            Branch: ${{ github.ref_name }}
            Workflow URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}